import type { UUID } from "crypto";

// Leaderboard Typing

export type LeaderboardResponse<P extends keyof LeaderboardRegistry> = {
	leaderboards: (LeaderboardRegistry[P] & { user_meta: PlayerGeneral })[];
	total: number;
	total_pages: number;
	page: number;
	page_size: number;
};

export type LeaderboardRegistry = {
	"/bedwars/master": BedwarsStatsMaster & {
		overall_final_kills_bedwars: number;
		overall_final_deaths_bedwars: number;
		overall_beds_broken_bedwars: number;
		overall_beds_lost_bedwars: number;
		overall_kills_bedwars: number;
		overall_deaths_bedwars: number;
		overall_wins_bedwars: number;
		overall_losses_bedwars: number;
		experience: number;
	};
};

export type StatsApiKeys<G extends keyof LeaderboardRegistry> = keyof LeaderboardRegistry[G];

// Leaderboard Models

export type PlayerGeneral = {
	player_id: UUID;
	display_name: string;
	last_updated: string;
	plus_colour: string;
	player_rank: string;
};

export type BedwarsStatsMaster = {
	wins_bedwars: number;
	losses_bedwars: number;
	games_played_bedwars: number;
	final_kills_bedwars: number;
	final_deaths_bedwars: number;
	beds_broken_bedwars: number;
	beds_lost_bedwars: number;
	kills_bedwars: number;
	deaths_bedwars: number;
	Experience: number;
	overall_bblr: number | null;
	overall_wlr: number | null;
	overall_fkdr: number | null;
	overall_kdr: number | null;
	eight_one_wins_bedwars: number;
	eight_one_losses_bedwars: number;
	eight_one_final_kills_bedwars: number;
	eight_one_final_deaths_bedwars: number;
	eight_one_beds_broken_bedwars: number;
	eight_one_beds_lost_bedwars: number;
	eight_one_kills_bedwars: number;
	eight_one_deaths_bedwars: number;
	eight_one_wlr: number | null;
	eight_one_fkdr: number | null;
	eight_one_bblr: number | null;
	eight_one_kdr: number | null;
	eight_two_wins_bedwars: number;
	eight_two_losses_bedwars: number;
	eight_two_final_kills_bedwars: number;
	eight_two_final_deaths_bedwars: number;
	eight_two_beds_broken_bedwars: number;
	eight_two_beds_lost_bedwars: number;
	eight_two_kills_bedwars: number;
	eight_two_deaths_bedwars: number;
	eight_two_wlr: number | null;
	eight_two_fkdr: number | null;
	eight_two_bblr: number | null;
	eight_two_kdr: number | null;
	four_three_wins_bedwars: number;
	four_three_losses_bedwars: number;
	four_three_final_kills_bedwars: number;
	four_three_final_deaths_bedwars: number;
	four_three_beds_broken_bedwars: number;
	four_three_beds_lost_bedwars: number;
	four_three_kills_bedwars: number;
	four_three_deaths_bedwars: number;
	four_three_wlr: number | null;
	four_three_fkdr: number | null;
	four_three_bblr: number | null;
	four_three_kdr: number | null;
	four_four_wins_bedwars: number;
	four_four_losses_bedwars: number;
	four_four_final_kills_bedwars: number;
	four_four_final_deaths_bedwars: number;
	four_four_beds_broken_bedwars: number;
	four_four_beds_lost_bedwars: number;
	four_four_kills_bedwars: number;
	four_four_deaths_bedwars: number;
	four_four_wlr: number | null;
	four_four_fkdr: number | null;
	four_four_bblr: number | null;
	four_four_kdr: number | null;
	two_four_wins_bedwars: number;
	two_four_losses_bedwars: number;
	two_four_final_kills_bedwars: number;
	two_four_final_deaths_bedwars: number;
	two_four_beds_broken_bedwars: number;
	two_four_beds_lost_bedwars: number;
	two_four_kills_bedwars: number;
	two_four_deaths_bedwars: number;
	two_four_wlr: number | null;
	two_four_fkdr: number | null;
	two_four_bblr: number | null;
	two_four_kdr: number | null;
	castle_wins_bedwars: number;
	castle_losses_bedwars: number;
	castle_final_kills_bedwars: number;
	castle_final_deaths_bedwars: number;
	castle_beds_broken_bedwars: number;
	castle_beds_lost_bedwars: number;
	castle_kills_bedwars: number;
	castle_deaths_bedwars: number;
	castle_wlr: number | null;
	castle_fkdr: number | null;
	castle_bblr: number | null;
	castle_kdr: number | null;
	eight_two_armed_wins_bedwars: number;
	eight_two_armed_losses_bedwars: number;
	eight_two_armed_final_kills_bedwars: number;
	eight_two_armed_final_deaths_bedwars: number;
	eight_two_armed_beds_broken_bedwars: number;
	eight_two_armed_beds_lost_bedwars: number;
	eight_two_armed_kills_bedwars: number;
	eight_two_armed_deaths_bedwars: number;
	eight_two_armed_wlr: number | null;
	eight_two_armed_fkdr: number | null;
	eight_two_armed_bblr: number | null;
	eight_two_armed_kdr: number | null;
	four_four_armed_wins_bedwars: number;
	four_four_armed_losses_bedwars: number;
	four_four_armed_final_kills_bedwars: number;
	four_four_armed_final_deaths_bedwars: number;
	four_four_armed_beds_broken_bedwars: number;
	four_four_armed_beds_lost_bedwars: number;
	four_four_armed_kills_bedwars: number;
	four_four_armed_deaths_bedwars: number;
	four_four_armed_wlr: number | null;
	four_four_armed_fkdr: number | null;
	four_four_armed_bblr: number | null;
	four_four_armed_kdr: number | null;
	eight_two_lucky_wins_bedwars: number;
	eight_two_lucky_losses_bedwars: number;
	eight_two_lucky_final_kills_bedwars: number;
	eight_two_lucky_final_deaths_bedwars: number;
	eight_two_lucky_beds_broken_bedwars: number;
	eight_two_lucky_beds_lost_bedwars: number;
	eight_two_lucky_kills_bedwars: number;
	eight_two_lucky_deaths_bedwars: number;
	eight_two_lucky_wlr: number | null;
	eight_two_lucky_fkdr: number | null;
	eight_two_lucky_bblr: number | null;
	eight_two_lucky_kdr: number | null;
	four_four_lucky_wins_bedwars: number;
	four_four_lucky_losses_bedwars: number;
	four_four_lucky_final_kills_bedwars: number;
	four_four_lucky_final_deaths_bedwars: number;
	four_four_lucky_beds_broken_bedwars: number;
	four_four_lucky_beds_lost_bedwars: number;
	four_four_lucky_kills_bedwars: number;
	four_four_lucky_deaths_bedwars: number;
	four_four_lucky_wlr: number | null;
	four_four_lucky_fkdr: number | null;
	four_four_lucky_bblr: number | null;
	four_four_lucky_kdr: number | null;
	eight_one_rush_wins_bedwars: number;
	eight_one_rush_losses_bedwars: number;
	eight_one_rush_final_kills_bedwars: number;
	eight_one_rush_final_deaths_bedwars: number;
	eight_one_rush_beds_broken_bedwars: number;
	eight_one_rush_beds_lost_bedwars: number;
	eight_one_rush_kills_bedwars: number;
	eight_one_rush_deaths_bedwars: number;
	eight_one_rush_wlr: number | null;
	eight_one_rush_fkdr: number | null;
	eight_one_rush_bblr: number | null;
	eight_one_rush_kdr: number | null;
	eight_two_rush_wins_bedwars: number;
	eight_two_rush_losses_bedwars: number;
	eight_two_rush_final_kills_bedwars: number;
	eight_two_rush_final_deaths_bedwars: number;
	eight_two_rush_beds_broken_bedwars: number;
	eight_two_rush_beds_lost_bedwars: number;
	eight_two_rush_kills_bedwars: number;
	eight_two_rush_deaths_bedwars: number;
	eight_two_rush_wlr: number | null;
	eight_two_rush_fkdr: number | null;
	eight_two_rush_bblr: number | null;
	eight_two_rush_kdr: number | null;
	four_four_rush_wins_bedwars: number;
	four_four_rush_losses_bedwars: number;
	four_four_rush_final_kills_bedwars: number;
	four_four_rush_final_deaths_bedwars: number;
	four_four_rush_beds_broken_bedwars: number;
	four_four_rush_beds_lost_bedwars: number;
	four_four_rush_kills_bedwars: number;
	four_four_rush_deaths_bedwars: number;
	four_four_rush_wlr: number | null;
	four_four_rush_fkdr: number | null;
	four_four_rush_bblr: number | null;
	four_four_rush_kdr: number | null;
	eight_one_ultimate_wins_bedwars: number;
	eight_one_ultimate_losses_bedwars: number;
	eight_one_ultimate_final_kills_bedwars: number;
	eight_one_ultimate_final_deaths_bedwars: number;
	eight_one_ultimate_beds_broken_bedwars: number;
	eight_one_ultimate_beds_lost_bedwars: number;
	eight_one_ultimate_kills_bedwars: number;
	eight_one_ultimate_deaths_bedwars: number;
	eight_one_ultimate_wlr: number | null;
	eight_one_ultimate_fkdr: number | null;
	eight_one_ultimate_bblr: number | null;
	eight_one_ultimate_kdr: number | null;
	eight_two_ultimate_wins_bedwars: number;
	eight_two_ultimate_losses_bedwars: number;
	eight_two_ultimate_final_kills_bedwars: number;
	eight_two_ultimate_final_deaths_bedwars: number;
	eight_two_ultimate_beds_broken_bedwars: number;
	eight_two_ultimate_beds_lost_bedwars: number;
	eight_two_ultimate_kills_bedwars: number;
	eight_two_ultimate_deaths_bedwars: number;
	eight_two_ultimate_wlr: number | null;
	eight_two_ultimate_fkdr: number | null;
	eight_two_ultimate_bblr: number | null;
	eight_two_ultimate_kdr: number | null;
	four_four_ultimate_wins_bedwars: number;
	four_four_ultimate_losses_bedwars: number;
	four_four_ultimate_final_kills_bedwars: number;
	four_four_ultimate_final_deaths_bedwars: number;
	four_four_ultimate_beds_broken_bedwars: number;
	four_four_ultimate_beds_lost_bedwars: number;
	four_four_ultimate_kills_bedwars: number;
	four_four_ultimate_deaths_bedwars: number;
	four_four_ultimate_wlr: number | null;
	four_four_ultimate_fkdr: number | null;
	four_four_ultimate_bblr: number | null;
	four_four_ultimate_kdr: number | null;
	eight_one_voidless_wins_bedwars: number;
	eight_one_voidless_losses_bedwars: number;
	eight_one_voidless_final_kills_bedwars: number;
	eight_one_voidless_final_deaths_bedwars: number;
	eight_one_voidless_beds_broken_bedwars: number;
	eight_one_voidless_beds_lost_bedwars: number;
	eight_one_voidless_kills_bedwars: number;
	eight_one_voidless_deaths_bedwars: number;
	eight_one_voidless_wlr: number | null;
	eight_one_voidless_fkdr: number | null;
	eight_one_voidless_bblr: number | null;
	eight_one_voidless_kdr: number | null;
	eight_two_voidless_wins_bedwars: number;
	eight_two_voidless_losses_bedwars: number;
	eight_two_voidless_final_kills_bedwars: number;
	eight_two_voidless_final_deaths_bedwars: number;
	eight_two_voidless_beds_broken_bedwars: number;
	eight_two_voidless_beds_lost_bedwars: number;
	eight_two_voidless_kills_bedwars: number;
	eight_two_voidless_deaths_bedwars: number;
	eight_two_voidless_wlr: number | null;
	eight_two_voidless_fkdr: number | null;
	eight_two_voidless_bblr: number | null;
	eight_two_voidless_kdr: number | null;
	four_four_voidless_wins_bedwars: number;
	four_four_voidless_losses_bedwars: number;
	four_four_voidless_final_kills_bedwars: number;
	four_four_voidless_final_deaths_bedwars: number;
	four_four_voidless_beds_broken_bedwars: number;
	four_four_voidless_beds_lost_bedwars: number;
	four_four_voidless_kills_bedwars: number;
	four_four_voidless_deaths_bedwars: number;
	four_four_voidless_wlr: number | null;
	four_four_voidless_fkdr: number | null;
	four_four_voidless_bblr: number | null;
	four_four_voidless_kdr: number | null;
	eight_two_swap_wins_bedwars: number;
	eight_two_swap_losses_bedwars: number;
	eight_two_swap_final_kills_bedwars: number;
	eight_two_swap_final_deaths_bedwars: number;
	eight_two_swap_beds_broken_bedwars: number;
	eight_two_swap_beds_lost_bedwars: number;
	eight_two_swap_kills_bedwars: number;
	eight_two_swap_deaths_bedwars: number;
	eight_two_swap_wlr: number | null;
	eight_two_swap_fkdr: number | null;
	eight_two_swap_bblr: number | null;
	eight_two_swap_kdr: number | null;
	four_four_swap_wins_bedwars: number;
	four_four_swap_losses_bedwars: number;
	four_four_swap_final_kills_bedwars: number;
	four_four_swap_final_deaths_bedwars: number;
	four_four_swap_beds_broken_bedwars: number;
	four_four_swap_beds_lost_bedwars: number;
	four_four_swap_kills_bedwars: number;
	four_four_swap_deaths_bedwars: number;
	four_four_swap_wlr: number | null;
	four_four_swap_fkdr: number | null;
	four_four_swap_bblr: number | null;
	four_four_swap_kdr: number | null;
	eight_two_underworld_wins_bedwars: number;
	eight_two_underworld_losses_bedwars: number;
	eight_two_underworld_final_kills_bedwars: number;
	eight_two_underworld_final_deaths_bedwars: number;
	eight_two_underworld_beds_broken_bedwars: number;
	eight_two_underworld_beds_lost_bedwars: number;
	eight_two_underworld_kills_bedwars: number;
	eight_two_underworld_deaths_bedwars: number;
	eight_two_underworld_wlr: number | null;
	eight_two_underworld_fkdr: number | null;
	eight_two_underworld_bblr: number | null;
	eight_two_underworld_kdr: number | null;
	four_four_underworld_wins_bedwars: number;
	four_four_underworld_losses_bedwars: number;
	four_four_underworld_final_kills_bedwars: number;
	four_four_underworld_final_deaths_bedwars: number;
	four_four_underworld_beds_broken_bedwars: number;
	four_four_underworld_beds_lost_bedwars: number;
	four_four_underworld_kills_bedwars: number;
	four_four_underworld_deaths_bedwars: number;
	four_four_underworld_wlr: number | null;
	four_four_underworld_fkdr: number | null;
	four_four_underworld_bblr: number | null;
	four_four_underworld_kdr: number | null;
	eight_one_oneblock_wins_bedwars: number;
	eight_one_oneblock_losses_bedwars: number;
	eight_one_oneblock_final_kills_bedwars: number;
	eight_one_oneblock_final_deaths_bedwars: number;
	eight_one_oneblock_beds_broken_bedwars: number;
	eight_one_oneblock_beds_lost_bedwars: number;
	eight_one_oneblock_kills_bedwars: number;
	eight_one_oneblock_deaths_bedwars: number;
	eight_one_oneblock_wlr: number | null;
	eight_one_oneblock_fkdr: number | null;
	eight_one_oneblock_bblr: number | null;
	eight_one_oneblock_kdr: number | null;
	slumber_tickets_total: number;
	slumber_tickets_current: number;
	iron_resources_collected_bedwars: number;
	gold_resources_collected_bedwars: number;
	diamond_resources_collected_bedwars: number;
	emerald_resources_collected_bedwars: number;
	coins: number;
	total_challenges_completed: number;
	bw_unique_challenges_completed: number;
} & { player_id: UUID; last_updated: string; user_meta: PlayerGeneral };
